src/SKF.WebApplication/Models/BenefitModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SKF.WebApplication.Models
{
    public class BenefitModel
    {
        public int ID { get; set; }
        public Nullable<int> AssociatedMarkovStateID { get; set; }
        public string BenefitType { get; set; }
        public Nullable<bool> AddSubtract { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}

src/SKF.WebApplication/Models/ErrorViewModel.cs
using System;

namespace SKF.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/SKF.WebApplication/Models/MarkovStatesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SKF.WebApplication.Models
{
    public class MarkovStatesModel
    {
        
        public int Applicable_ModelID { get; set; }
        public int To_StateID { get; set; }
        public int From_StateID { get; set; }
        public int Period { get; set; }
        public decimal Value { get; set; }
    }
}

src/SKF.WebApplication/Controllers/BenefitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AML.Infrastructure.Data.EF;
using Microsoft.AspNetCore.Mvc;
using SKF.WebApplication.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SKF.WebApplication.Controllers
{
    public class BenefitController : Controller
    {
        //private readonly ActuarialValuationsEntities _aiValuationsContext;
        //public BenefitController(ActuarialValuationsEntities aiValuationsContext)
        //{
        //    _aiValuationsContext = aiValuationsContext;
        //}
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            //List<Benefit> lst = new List<Benefit>();
            //lst = (from benefit in _aiValuationsContext.Benefits
            //       select benefit).ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(BenefitModel obj)
        {
            return View();
        }
    }
}

src/SKF.WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SKF.WebApplication.Models;

namespace SKF.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SKF.WebApplication/Controllers/MarkovStatesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AML.infrastructure.Data.Dto;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SKF.WebApplication.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SKF.WebApplication.Controllers
{
    public class MarkovStatesController : Controller
    {


        private readonly IHostingEnvironment _appEnvironment;

        public MarkovStatesController(IHostingEnvironment appEnvironment)

        {

            //----< Init: Controller >----

            _appEnvironment = appEnvironment;

            //----</ Init: Controller >----

        }



        // GET: /<controller>/
        public IActionResult Index()
        {

            MarkovStatesDto objMarkovStatesDto = new MarkovStatesDto()
            {

                Applicable_Model_ID = 100,
                From_State_ID = 1,
                To_State_ID = 2,
                Period = 1,
                Value = 0.01m
            };
            //var obj = new MarkovStatesWriter.Write(objMarkovStatesDto);

            return View();
        }
        [HttpGet]
        public IActionResult CreateMarkovStates()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateMarkovStates(MarkovStatesModel obj)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadCSVFile1(List<IFormFile> files)
        {
            long size = files.Sum(f => f.Length);

            // full path to file in temp location
            var filePath = Path.GetTempFileName();

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            // process uploaded files
            // Don't rely on or trust the FileName property without validation.

            return Ok(new { count = files.Count, size, filePath });
        }


       [HttpPost] //Postback
        public async Task<IActionResult> UploadCSVFile(IFormFile file)
        {

            //--------< Upload_ImageFile() >--------

            //< check >

            if (file == null || file.Length == 0) return Content("file not selected");

            //</ check >

            List<MarkovStatesModel> markovStatesModel = new List<MarkovStatesModel>();
            var filepath = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        file.FileName);

            using (var stream = new FileStream(filepath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }


            //Read the contents of CSV file.
            string csvData = System.IO.File.ReadAllText(filepath);

            //Execute a loop over the rows.
            foreach (string row in csvData.Split('\n'))
            {
                if (!string.IsNullOrEmpty(row))
                {
                    markovStatesModel.Add(new MarkovStatesModel
                    {
                         To_StateID = Convert.ToInt32(row.Split(',')[0]),
                        From_StateID = Convert.ToInt32(row.Split(',')[1]),
                        Period = Convert.ToInt32(row.Split(',')[2]),
                        Value= Convert.ToDecimal(row.Split(',')[3]),
                    });
                }
            }
            //< output >

            ViewData["FilePath"] = filepath;

            return View();

            //</ output >

            //--------</ Upload_ImageFile() >--------

        }
    }


}

src/SKF.WebApplication/Views/Benefit/Create.cshtml
@model SKF.WebApplication.Models.BenefitModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Benefit</h2>

<h4>Benefit Model</h4>
<hr />
@*<div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ID" class="control-label"></label>
                    <input asp-for="ID" class="form-control" />
                    <span asp-validation-for="ID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AssociatedMarkovStateID" class="control-label"></label>
                    <input asp-for="AssociatedMarkovStateID" class="form-control" />
                    <span asp-validation-for="AssociatedMarkovStateID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BenefitType" class="control-label"></label>
                    <input asp-for="BenefitType" class="form-control" />
                    <span asp-validation-for="BenefitType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AddSubtract" class="control-label"></label>
                    <input asp-for="AddSubtract" class="form-control" />
                    <span asp-validation-for="AddSubtract" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Value" class="control-label"></label>
                    <input asp-for="Value" class="form-control" />
                    <span asp-validation-for="Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>*@
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="AssociatedMark">Associated Mark</label>
            <input type="text" class="form-control" id="AssociatedMark" asp-for="AssociatedMarkovStateID" placeholder="Associated Mark">
            <span asp-validation-for="ID" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="BenefitType">Benefit Type</label>
            <input type="text" class="form-control" id="BenefitType" asp-for="BenefitType" placeholder="BenefitType">
            <span asp-validation-for="BenefitType" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="AddSubtract">Add Subtract</label>
            <input type="text" class="form-control" asp-for="AddSubtract" id="AddSubtract" placeholder="Add Subtract">
            <span asp-validation-for="AddSubtract" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="Value">Value</label>
            <input type="text" class="form-control" asp-for="Value" id="Value" placeholder="Value">
            <span asp-validation-for="Value" class="text-danger"></span>
        </div>
    </div>
    <input type="submit" value="Create" class="btn btn-dark btn-block" />    
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SKF.WebApplication/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/SKF.WebApplication/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/SKF.WebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/SKF.WebApplication/Views/MarkovStates/CreateMarkovStates.cshtml
@model SKF.WebApplication.Models.MarkovStatesModel

@{
    ViewData["Title"] = "CreateMarkovStates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Markov States</h2>

<h4>Markov States Model</h4>
<hr />

@*<div class="row">
        <div class="col-md-4">
            <form asp-action="CreateMarkovStates">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Applicable Model ID</label>
                    <input asp-for="Applicable_ModelID" class="form-control" />
                    <span asp-validation-for="Applicable_ModelID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">To State ID</label>
                    <input asp-for="To_StateID" class="form-control" />
                    <span asp-validation-for="To_StateID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="From_StateID" class="control-label"> From State ID</label>
                    <input asp-for="From_StateID" class="form-control" />
                    <span asp-validation-for="From_StateID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Period" class="control-label"></label>
                    <input asp-for="Period" class="form-control" />
                    <span asp-validation-for="Period" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Value" class="control-label"></label>
                    <input asp-for="Value" class="form-control" />
                    <span asp-validation-for="Value" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>*@


<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group col-md-12">
        <label for="ApplicableModule">Application Module</label>
        <input type="text" class="form-control" id="ApplicableModule" asp-for="Applicable_ModelID" placeholder="Applicable Module">
        <span asp-validation-for="Applicable_ModelID" class="text-danger"></span>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="FromStateID">From State ID</label>
            <input type="text" class="form-control" id="FromStateID" asp-for="From_StateID" placeholder="From State ID">
            <span asp-validation-for="From_StateID" class="text-danger"></span>

        </div>
        <div class="form-group col-md-6">
            <label for="ToStateID">To State ID</label>
            <input type="text" class="form-control" id="ToStateID" asp-for="To_StateID" placeholder="To State ID">
            <span asp-validation-for="To_StateID" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="Period">Period</label>
            <input type="text" class="form-control" id="Period" asp-for="Period" placeholder="Period">
            <span asp-validation-for="Period" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label for="Value">Value</label>
            <input type="text" class="form-control" id="Value" asp-for="Value" placeholder="Value">
            <span asp-validation-for="Value" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group col-md-12">
        <input type="submit" value="Create" class="btn btn-dark btn-block" formaction="/MarkovStates/CreateMarkovStates" />
    </div>
    @*<div class="form-group">
            <div class="col-md-10">
                <p>Upload one or more files using this form:</p>
                <input type="file" name="files" multiple />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Upload" />
            </div>
        </div>*@
    <div class="custom-file mb-3">
        <input type="file" class="custom-file-input" id="customFile" name="file">
        <label class="custom-file-label" for="customFile">Choose file</label>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary" formaction="/MarkovStates/UploadCSVFile">Submit</button>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</form>

<label>Uploaded File= @ViewData["FilePath"]</label>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SKF.WebApplication/Views/MarkovStates/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1>Welcome</h1>

<p>Hey Team,</p>

src/SKF.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Actuarial Valuations</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        @*<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Actuarial Valuations</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="MarkovStates" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="MarkovStates" asp-action="CreateMarkovStates">Markov States Create</a></li>
                    <li><a asp-area="" asp-controller="Benefit" asp-action="Create">Benefit Create</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Actuarial Valuations</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        @*<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/popper.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>     

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>